# Generated by Django 4.1.2 on 2022-10-19 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lifestyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('migrates', models.BooleanField()),
                ('lifestyle', models.CharField(choices=[('T', 'Terrestrial'), ('O', 'Oviparous'), ('A', 'Arboreal'), ('C', 'Congregatory'), ('N', 'Nomadic')], default='T', max_length=3)),
                ('finch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.finch')),
            ],
        ),
    ]
