# Generated by Django 4.1.2 on 2022-10-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_finch_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifestyle',
            name='migrates',
            field=models.BooleanField(choices=[(1, 'Yes'), (2, 'No')], default=[2]),
        ),
    ]
