# Generated by Django 4.1.2 on 2022-10-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_lifestyle_migrates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifestyle',
            name='lifestyle',
            field=models.CharField(choices=[('T', 'Terrestrial'), ('O', 'Oviparous'), ('A', 'Arboreal'), ('C', 'Congregatory'), ('N', 'Nomadic')], default='T', max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyle',
            name='migrates',
            field=models.CharField(choices=[(1, 'Yes'), (2, 'No'), (3, '')], default=0, max_length=1),
        ),
    ]
