# Generated by Django 4.1.2 on 2022-10-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_accessory_alter_lifestyle_migrates_finch_accessories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessory',
            old_name='type',
            new_name='name',
        ),
    ]
